sudo: required

services:
  - docker

before_install:
  - docker build -t ranjithjagadees/docker-react -f Dockerfile.dev .

script:
  - docker run ranjithjagadees/docker-react yarn run test -- --coverage
